--- #YAML:1.0
name:                CGI-Application-Plugin-SuperForm
version:             0.5
abstract:            ~
license:             perl
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI::Application:              3
    HTML::SuperForm:               1.06
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
